name: .NET Framework Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore
        run: nuget restore

      - name: Build
        run: msbuild /p:Configuration=Release /p:Platform="Any CPU" /p:TargetFrameworkVersion=v4.6.2 GARbro.sln

      - name: Publish Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: GARbro-Mod-ci-build
          path: ./bin/Release